core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="index"),
    path("courses/", views.CoursesListView.as_view(), name="course_list"),
    path("courses/create/", views.CourseCreateView.as_view(), name="course_create"),
    path("courses/<slug:pk>/", views.CourseDetailView.as_view(), name="course_detail"),
    path(
        "course_content/video/<slug:lecture_id>/",
        views.lecture_video_view,
        name="lecture_video",
    ),
    path(
        "course_content/<slug:pk>/",
        views.CourseContentView.as_view(),
        name="course_content",
    ),
    path(
        "lectures/create/",
        views.CourseLectureCreateView.as_view(),
        name="lecture_create",
    ),
    path(
        "lectures/delete/<slug:pk>/",
        views.CourseLectureDeleteView.as_view(),
        name="lecture_delete",
    ),
    path(
        "lecture/<slug:pk>/edit/",
        views.CourseLectureEditView.as_view(),
        name="lecture_edit",
    ),
    path(
        "creator_coures/<slug:pk>/",
        views.CreatorCourseDetailView.as_view(),
        name="creator_course_detail",
    ),
    path(
        "section/<slug:pk>/delete",
        views.CourseSectionDeleteView.as_view(),
        name="section_delete",
    ),
    path("cart/", views.CartOperations.as_view(), name="cart"),
    path("user_courses/", views.UserCourseListView.as_view(), name="user_courses"),
    path("created_courses/", views.CreatedCoursesListView.as_view(), name="my_courses"),
    path("test/", views.handle_successful_payment, name="transaction_success"),
]

udemy/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import register
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/register/", register, name="register"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.core.validators import (
    FileExtensionValidator,
    MaxValueValidator,
    MinValueValidator,
    validate_image_file_extension,
)
import logging
from django.db import models
import uuid
from django.contrib.auth.models import User
from django.db.models import Avg, Max
from django.urls import reverse_lazy
from core.transactions import chapa


# Create your models here.
class BaseModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class CourseCategory(BaseModel):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


def get_course_preview_file_path(instance, filename):
    return f"courses/{instance.id}/preview/{filename}"


def get_course_thumbnail_file_path(instance, filename):
    return f"courses/{instance.id}/thumbnail/{filename}"


class Course(BaseModel):
    title = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    short_description = models.CharField(max_length=100)
    description = models.TextField()
    language = models.CharField(max_length=100)
    price = models.DecimalField(decimal_places=2, max_digits=5)
    preview = models.FileField(
        upload_to=get_course_preview_file_path,
        validators=[FileExtensionValidator(allowed_extensions=["mp4", "mkv", "webm"])],
    )
    thumbnail = models.ImageField(
        upload_to=get_course_thumbnail_file_path,
        validators=[validate_image_file_extension],
        null=True,
    )
    category = models.ForeignKey(CourseCategory, on_delete=models.CASCADE)
    enrolled_users = models.ManyToManyField(to=User, related_name="enrolled_courses")

    class Meta:
        ordering = ["-updated_at"]

    @property
    def average_rating(self):
        average = self.courserating_set.aggregate(avg_val=Avg("rating"))["avg_val"]
        if not average:
            return 0.0

        return round(average, 2)

    @property
    def checked_star(self):
        return (round(self.average_rating * 2) / 2) * 2

    def __str__(self):
        return self.title


class CourseRequirement(BaseModel):
    course = models.ForeignKey(
        Course, on_delete=models.CASCADE, related_name="requirements"
    )
    description = models.TextField(verbose_name="Requirement")

    def __str__(self):
        return self.description


class CourseAudience(BaseModel):
    course = models.ForeignKey(
        Course, on_delete=models.CASCADE, related_name="audience"
    )
    description = models.TextField(verbose_name="Who is this course for?")

    def __str__(self):
        return self.description


class CourseSection(BaseModel):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    order = models.IntegerField(default=0)

    def __str__(self) -> str:
        return f"{self.title} -> {self.course.title}"


def get_course_lecture_file_path(instance, filename):
    return f"courses/{instance.section.course.id}/sections/{instance.section.id}/lectures/{instance.order}"


class CourseLecture(BaseModel):
    section = models.ForeignKey(CourseSection, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    order = models.IntegerField()
    content = models.FileField(upload_to=get_course_lecture_file_path, max_length=500)
    previewable = models.BooleanField(default=False)

    @property
    def content_type(self):
        return self.content.content_type

    def save(self, *args, **kwargs) -> None:
        if self.order is None:
            last_order = CourseLecture.objects.filter(section=self.section).aggregate(
                order=Max("order")
            )["order"]
            if not last_order:
                last_order = 0
            self.order = last_order + 1
        return super().save(*args, **kwargs)


class CourseRating(BaseModel):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(5)]
    )
    review = models.TextField()


class TransactionStatus(models.TextChoices):
    CREATED = "Created", "CREATED"
    PENDING = "Pending", "PENDING"
    SUCCESS = "Success", "SUCCESS"
    FAILED = "Failed", "FAILED"


class Transaction(BaseModel):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="transactions"
    )
    courses = models.ManyToManyField(Course)
    amount = models.FloatField()
    currency = models.CharField(max_length=25, default="ETB")

    payment_title = models.CharField(max_length=255, default="Payment")
    description = models.TextField(null=True, blank=True)

    status = models.CharField(
        max_length=50, choices=TransactionStatus, default=TransactionStatus.CREATED
    )

    response_dump = models.JSONField(
        default=dict, blank=True
    )  # incase the response is valuable in the future
    checkout_url = models.URLField(null=True, blank=True)

    @staticmethod
    def initialize(user: User, amount: float, courses: list[Course]):
        transaction = Transaction(user=user, amount=amount)
        transaction.save()
        for course in courses:
            transaction.courses.add(course)
        transaction.save()
        response = chapa.initialize(
            email=user.email,
            amount=amount,
            first_name=user.first_name,
            last_name=user.last_name,
            tx_ref=transaction.id,
            customization={"title": "Udemy"},
            return_url="http://localhost:8000" + reverse_lazy("core:index"),
            callback_url="http://localhost:8000"
            + reverse_lazy("core:transaction_success"),
        )
        if response["status"] == "failed":
            transaction.status = TransactionStatus.FAILED
            transaction.save()
            return transaction

        transaction.checkout_url = response["data"]["checkout_url"]
        transaction.save()
        return transaction

core/forms.py
from django import forms
from django.forms.widgets import Select, TextInput
from django.utils.safestring import mark_safe

from core.models import Course, CourseAudience, CourseLecture, CourseRequirement


class DatalistTextInput(TextInput):
    def __init__(self, attrs=None, datalist=[]):
        if attrs is not None:
            attrs["datalist"] = "__".join(datalist)

        super().__init__(attrs)
        if "list" not in self.attrs or "datalist" not in self.attrs:
            raise ValueError(
                'DatalistTextInput widget is missing required attrs "list" or "datalist"'
            )

        self.datalist_name = self.attrs["list"]

        self.datalist = datalist

    def render(self, **kwargs):
        part1 = super().render(**kwargs)
        opts = " ".join([f"<option>{x}</option>" for x in self.datalist])
        part2 = f'<datalist id="{self.datalist_name}">{opts}</datalist>'
        return part1 + mark_safe(part2)


class SearchSelectInput(Select):
    def __init__(
        self, attrs=None, options: list[dict[str, str]] = None, *args, **kwargs
    ):
        super().__init__(*args, attrs, **kwargs)


class TestDatalist(forms.Form):
    foo = forms.CharField(
        max_length=10,
        widget=DatalistTextInput(
            attrs={
                "list": "foolist",
                "class": "input input-bordered",
            },
            datalist=["foo", "bar", "baz", "quux"],
        ),
    )


# class BaseModelForm(forms.ModelForm):
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         for visible in self.visible_fields():
#             class_str = None
#             print(visible.widget_type)
#             match visible.widget_type:
#                 case "text" | "number":
#                     class_str = "input input-bordered"
#                 case "checkbox":
#                     class_str = "checkbox"
#                 case "select" | "selectmultiple":
#                     class_str = "select select-bordered"
#                 case "clearablefile":
#                     class_str = "file-input file-input-bordered"
#                 case _:
#                     class_str = "input input-bordered"
#
#             visible.field.widget.attrs["class"] = class_str


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        exclude = ["user", "enrolled_users"]
        widgets = {
            "preview": forms.FileInput(
                attrs={"accept": "video/mp4,video/webm,video/ogg,video/mpeg"}
            )
        }


class CourseRequirementForm(forms.ModelForm):
    class Meta:
        model = CourseRequirement
        fields = ["description"]


class CourseAudienceForm(forms.ModelForm):
    class Meta:
        model = CourseAudience
        fields = ["description"]


class CourseLectureForm(forms.ModelForm):
    class Meta:
        model = CourseLecture
        exclude = ["id", "created_at", "updated_at", "order"]

core/templates/core/course_content.html
{% extends "base.html" %}

{% block content %}
    <div class="mx-8 mt-10">
        <ul class="space-y-8">
            {% for section in course.coursesection_set.all %}
                <li class="space-y-4">
                    <p class="text-center text-4xl">{{ section.title }}</p>
                    <ul class="ml-8 space-y-4">
                        {% for lecture in section.courselecture_set.all %}
                            <a href="{% url 'core:lecture_video' lecture_id=lecture.id %}"
                               class="bg-primary p-6 text-2xl flex justify-between hover:cursor-pointer transition-transform ease-in-out delay-75 hover:scale-x-105">
                                <p>{{ lecture.title }}</p>
                                <i data-feather="arrow-right" class="w-8"></i>
                            </a>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}

core/templates/core/course_create_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="post" class="form-control items-center" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="my-4">
            <h1 class="mb-5 font-bold text-3xl">Create A New Course</h1>
            {{ form|crispy }}
            <input type="submit" class="btn btn-primary">
        </div>
    </form>
{% endblock content %}

core/templates/core/course_creator_detail.html
{% extends "base.html" %}

{% block content %}
    <div class="p-8 mt-4"
         x-data="{'showModal': false}"
         @keydown.escape="showModal = false">
        <div class="fixed inset-0 z-30 flex items-center justify-center overflow-auto bg-black bg-opacity-50"
             x-show="showModal"
             x-cloak>
            <!-- Modal inner -->
            <div class="max-w-3xl px-6 py-4 mx-auto text-left bg-white rounded shadow-lg"
                 @click.away="showModal = false"
                 x-transition:enter="motion-safe:ease-out duration-300"
                 x-transition:enter-start="opacity-0 scale-90"
                 x-transition:enter-end="opacity-100 scale-100">
                <!-- Title / Close-->
                <div class="flex items-center justify-between">
                    <h5 class="mr-3 text-black max-w-none">Course Lecture</h5>

                    <button type="button" class="z-50 cursor-pointer" @click="showModal = false">
                        <i data-feather="x"></i>
                    </button>
                </div>

                <!-- content -->
                <form method="post"
                      enctype="multipart/form-data"
                      hx-post="{% url 'core:lecture_create' %}"
                      hx-swap="beforeend">
                    <div id="modal-content"></div>
                    <button class="btn btn-primary" @click="showModal = false">Submit</button>
                </form>
            </div>
        </div>

        <h1 class="text-center font-bold text-5xl">{{ course.title }}</h1>

        <div class="p-8 mt-5">
            <h1 class="text-center font-bold text-3xl">Course Sections</h1>
            <ul id="sections" class="grid md:lg-cols-2 lg:grid-cols-4 gap-4 mt-4">
                {% for section in course.coursesection_set.all %}
                    {% block section %}
                    <li id="section-{{ section.id }}" class="flex flex-col gap-2">
                            <div class="flex justify-around">
                                <p class="text-3xl text-center">{{ section.title }}</p>
                                <button hx-post="{% url 'core:section_delete' pk=section.id %}"
                                        hx-target="#section-{{ section.id }}"
                                        hx-swap="delete"
                                        hx-confirm="Are you sure you wish to delete this section?">
                                    <svg xmlns="http://www.w3.org/2000/svg"
                                         width="24"
                                         height="24"
                                         viewBox="0 0 24 24"
                                         fill="none"
                                         stroke="currentColor"
                                         stroke-width="2"
                                         stroke-linecap="round"
                                         stroke-linejoin="round"
                                         class="feather feather-trash-2 w-8 stroke-warning">
                                        <polyline points="3 6 5 6 21 6"></polyline>
                                        <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2">
                                        </path>
                                        <line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line>
                                    </svg>
                                </button>
                            </div>
                            <ul id="lecture-list-{{ section.id }}" class="flex flex-col gap-4 ml-4">
                                {% for lecture in section.courselecture_set.all %}
                                    {% block lecture %}
                                        <li id="lecture-{{ lecture.id }}" class="card w-96 bg-base-100 shadow-xl">
                                            <figure>
                                                <video controls>
                                                    <source src="{{ lecture.content.url }}">
                                                    Your browser doesn't support videos
                                                </video>
                                            </figure>
                                            <div class="card-body">
                                                <h2 class="card-title">{{ lecture.title }}</h2>
                                                <div class="card-actions justify-end">
                                                    <button hx-post="{% url 'core:lecture_delete' pk=lecture.id %}"
                                                            hx-target="#lecture-{{ lecture.id }}"
                                                            hx-swap="delete"
                                                            hx-confirm="Are you sure you wish to delete this lecture?">
                                                        <svg xmlns="http://www.w3.org/2000/svg"
                                                             width="24"
                                                             height="24"
                                                             viewBox="0 0 24 24"
                                                             fill="none"
                                                             stroke="currentColor"
                                                             stroke-width="2"
                                                             stroke-linecap="round"
                                                             stroke-linejoin="round"
                                                             class="feather feather-trash-2 w-8 stroke-warning">
                                                            <polyline points="3 6 5 6 21 6"></polyline>
                                                            <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2">
                                                            </path>
                                                            <line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line>
                                                        </svg>
                                                    </button>
                                                </div>
                                            </div>
                                        </li>
                                    {% endblock lecture %}
                                {% endfor %}
                            </ul>
                        </li>
                    {% endblock section %}
                {% endfor %}
            </ul>
            <div class="flex items-center justify-center gap-2 mt-10">
                <form hx-post="{% url 'core:creator_course_detail' pk=course.id %}"
                      hx-swap="beforeend"
                      hx-target="#sections"
                      hx-indicator="#section-spinner"
                      hx-on::after-request="this.reset()"
                      class="flex gap-2 items-center">
                    <input type="hidden" name="op-type" value="section">
                    <input class="input input-bordered input-sm"
                           type="text"
                           name="title"
                           placeholder="Section Title"
                           required
                           >
                    <button class="btn btn-secondary btn-sm" type="submit">
                        <i data-feather="plus"></i>
                        Add
                        <span id="section-spinner" class="loading loading-spinner app-indicator"></span>
                    </button>
                </form>

                <button hx-get="{% url 'core:lecture_create' %}"
                        class="btn btn-accent btn-sm"
                        @click="showModal = true"
                        hx-target="#modal-content">
                    <i data-feather="plus"></i>
                    Add Lecture
                </button>
            </div>

        </div>
        <div class="grid grid-cols-2 mt-8 gap-4">

            <div class="border border-primary p-8">
                <h1 class="text-center font-bold text-3xl">Course Requirements</h1>
                <ul id="requirements"
                    class="flex flex-col items-center justify-center list-disc mt-4">
                    {% for requirement in course.requirements.all %}
                        <li>{{ requirement.description }}</li>
                    {% endfor %}
                </ul>
                <form hx-post="{% url 'core:creator_course_detail' pk=course.id %}"
                      hx-swap="beforeend"
                      hx-target="#requirements"
                      hx-indicator="#spinner"
                      hx-on::after-request="this.reset()"
                      class="flex items-center justify-center gap-2 mt-10">
                    <input type="hidden" name="op-type" value="requirement">
                    <textarea name="description"
                              type="text"
                              class="textarea textarea-primary textarea-md"
                              required
                              placeholder="Description"></textarea>
                    <button class="btn btn-secondary btn-md" type="submit">
                        <i data-feather="plus"></i>
                        Add
                        <span id="spinner" class="loading loading-spinner app-indicator"></span>
                    </button>
                </form>
            </div>
            <div class="border border-primary p-8">
                <h1 class="text-center font-bold text-3xl">Course Audience</h1>
                <ul id="audiences"
                    class="flex flex-col items-center justify-center list-disc mt-4">
                    {% for audience in course.audience.all %}
                        <li>{{ audience.description }}</li>
                    {% endfor %}
                </ul>
                <form hx-post="{% url 'core:creator_course_detail' pk=course.id %}"
                      hx-swap="beforeend"
                      hx-target="#audiences"
                      hx-indicator="#audience-spinner"
                      hx-on::after-request="this.reset()"
                      class="flex items-center justify-center gap-2 mt-10">
                    <input type="hidden" name="op-type" value="audience">
                    <textarea name="description"
                              type="text"
                              class="textarea textarea-primary textarea-md"
                              required
                              placeholder="Description"></textarea>
                    <button class="btn btn-secondary btn-md" type="submit">
                        <i data-feather="plus"></i>
                        Add
                        <span id="audience-spinner" class="loading loading-spinner app-indicator"></span>
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

core/templates/core/course_detail.html
{% extends "base.html" %}
{% load core_filters %}
{% block content %}
    <div class="bg-secondary text-secondary-content flex items-center py-8 lg:py-24">
        <div class="flex flex-col gap-3 basis-1/2 ml-36">
            <h1 class="font-bold text-2xl text-secondary-content">{{ course.title }}</h1>
            <p class="break-all whitespace-normal">{{ course.short_description }}</p>
            <div class="flex gap-2 items-center">
                {% include "partials/course-rating.html" with course=course %}
                <span class="text-xs text-info">({{ course.courserating_set.count }} ratings)</span>
                <span class="text-xs">{{ course.enrolled_users.count }} students</span>
            </div>
            <p class="text-xs">
                Created by <span class="text-xs text-info">{{ course.user.first_name }} {{ course.user.last_name }}</span>
            </p>
            <div class="flex gap-4">
                <div class="flex items-center gap-2">
                    <i data-feather="alert-triangle" class="w-4"></i>
                    <p class="text-sm">Last updated {{ course.updated_at|date:"n/Y" }}</p>
                </div>
                <div class="flex items-center gap-2">
                    <i data-feather="globe" class="w-4"></i>
                    <span class="text-sm">English</span>
                </div>
            </div>
            <div id="course-actions" class="mt-8 flex gap-4 items-center">
                {% block course_actions %}
                    {% if user in course.enrolled_users.all %}
                        <a href="{% url 'core:course_content' pk=course.id %}"
                           class="btn btn-neutral">
                            View Course Content
                            <i data-feather="arrow-right" class="w-4"></i>
                        </a>
                    {% else %}
                        {% if not in_cart %}
                            <button hx-swap="delete"
                                    hx-target="this"
                                    hx-post="{% url 'core:cart' %}"
                                    hx-vals='{"operation": "add", "course_id": "{{ course.id }}"}'
                                    hx-indicator="#spinner"
                                    class="btn btn-primary">
                                <i data-feather="shopping-cart" class="w-4"></i>
                                Add to Cart
                                <span id="spinner" class="loading loading-spinner app-indicator"></span>
                            </button>
                        {% endif %}
                        <button class="btn btn-accent"
                                hx-target="#course-actions"
                                hx-post="{% url 'core:course_detail' pk=course.id %}"
                                hx-indicator="#bought-spinner">
                            Buy Now
                            <span id="bought-spinner" class="loading loading-spinner app-indicator"></span>
                        </button>
                    {% endif %}
                {% endblock course_actions %}
            </div>
        </div>
        <div class="basis-1/2 flex justify-center">
            <video class="max-w-sm rounded-lg shadow-2xl" controls>
                <source src="{{ course.preview.url }}">
                Your browser doesn't support videos
            </video>
        </div>
    </div>
    <div class="ml-8 md:ml-24 lg:ml-36 my-14 flex">
        <div class="basis-1/2 prose">
            <h2>Requirements</h2>
            <ul>
                {% for requirement in course.requirements.all %}
                    <li>{{ requirement }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="prose">
            <h2>Who this course is for</h2>
            <ul>
                {% for audience in course.audience.all %}<li>{{ audience }}</li>{% endfor %}
            </ul>
        </div>
    </div>
{% endblock content %}

core/templates/core/course_video_page.html
{% extends "base.html" %}
{% load static %}

{% block statics %}
    <script src="{% static 'js/videoControls.js' %}" defer></script>
{% endblock statics %}

{% block content %}
    <video controls class="w-full h-full">
        <source src="{{ lecture.content.url }}">
        Your browser doesn't support videos
    </video>
{% endblock content %}

core/templates/core/courselecture_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
    <form action="{% url 'core:lecture_edit' pk=lecture.id %}"
          method="post"
          enctype="multipart/form-data"
          class="flex items-center justify-center flex-col">
        <div>{{ form|crispy }}</div>
        <button class="btn btn-primary">Submit</button>
    </form>
{% endblock content %}

core/templates/core/my_courses.html
{% extends "base.html" %}
{% load static %}
{% load core_filters %}
{% block statics %}
    <link href="{% static "core/home.css" %}" rel="stylesheet">
{% endblock statics %}
{% block content %}
    <div class="flex items-center my-8 gap-4 px-8">
        <h1 class="text-3xl font-bold text-center text-primary-content flex-1">
            Your Courses
        </h1>
        <a class="btn btn-primary self-center" href="{% url 'core:course_create' %}">
            <i data-feather="plus"></i>
            Create Course
        </a>
    </div>
    <main id="main-course-list"
          class="m-4 md:m-8 flex flex-wrap lg:grid lg:grid-cols-4 gap-4"
          hx-get="{% url 'core:my_courses' %}"
          hx-swap="innerHTML"
          hx-trigger="load"
          hx-indicator=".course-skeleton"
          >
        {% block course_list %}
            {% for i in 8|times %}
                <div id="#course-skeleton-{{ i }}"
                     hx-preserve
                     class="card w-96 bg-base-100 shadow-xl py-4 app-indicator course-skeleton">
                    <figure>
                        <div class="skeleton h-32 w-28"></div>
                    </figure>
                    <div class="card-body">
                        <div class="skeleton h-4 w-36"></div>
                        <div class="skeleton h-4 w-20 mt-2"></div>
                        <div class="skeleton h-4 w-full mt-10"></div>
                        <div class="skeleton h-4 w-full "></div>
                        <div class="skeleton h-4 w-full "></div>
                        <div class="skeleton h-4 w-full "></div>
                        <div class="flex justify-between mt-10">
                            <div class="skeleton h-2 w-28"></div>
                            <div class="skeleton h-2 w-28"></div>
                        </div>
                        <div class="skeleton h-2 w-28 mt-2"></div>
                        <div class="card-actions justify-end">
                            <div class="skeleton h-8 w-28"></div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% for course in courses %}
                {% include "partials/course.html" with is_creator=is_creator %}
            {% endfor %}
        {% endblock course_list %}
    </main>
{% endblock content %}