core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="index"),
    path("courses/", views.CoursesListView.as_view(), name="course_list"),
    path("courses/create/", views.CourseCreateView.as_view(), name="course_create"),
    path("courses/<slug:pk>/", views.CourseDetailView.as_view(), name="course_detail"),
    path(
        "course_content/video/<slug:lecture_id>/",
        views.lecture_video_view,
        name="lecture_video",
    ),
    path(
        "course_content/<slug:pk>/",
        views.CourseContentView.as_view(),
        name="course_content",
    ),
    path(
        "lectures/create/",
        views.CourseLectureCreateView.as_view(),
        name="lecture_create",
    ),
    path(
        "lectures/delete/<slug:pk>/",
        views.CourseLectureDeleteView.as_view(),
        name="lecture_delete",
    ),
    path(
        "lecture/<slug:pk>/edit/",
        views.CourseLectureEditView.as_view(),
        name="lecture_edit",
    ),
    path(
        "creator_coures/<slug:pk>/",
        views.CreatorCourseDetailView.as_view(),
        name="creator_course_detail",
    ),
    path(
        "section/<slug:pk>/delete",
        views.CourseSectionDeleteView.as_view(),
        name="section_delete",
    ),
    path("cart/", views.CartOperations.as_view(), name="cart"),
    path("user_courses/", views.UserCourseListView.as_view(), name="user_courses"),
    path("created_courses/", views.CreatedCoursesListView.as_view(), name="my_courses"),
    path("test/", views.handle_successful_payment, name="transaction_success"),
]

udemy/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import register
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/register/", register, name="register"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from django.forms.widgets import Select, TextInput
from django.utils.safestring import mark_safe

from core.models import Course, CourseAudience, CourseLecture, CourseRequirement


class DatalistTextInput(TextInput):
    def __init__(self, attrs=None, datalist=[]):
        if attrs is not None:
            attrs["datalist"] = "__".join(datalist)

        super().__init__(attrs)
        if "list" not in self.attrs or "datalist" not in self.attrs:
            raise ValueError(
                'DatalistTextInput widget is missing required attrs "list" or "datalist"'
            )

        self.datalist_name = self.attrs["list"]

        self.datalist = datalist

    def render(self, **kwargs):
        part1 = super().render(**kwargs)
        opts = " ".join([f"<option>{x}</option>" for x in self.datalist])
        part2 = f'<datalist id="{self.datalist_name}">{opts}</datalist>'
        return part1 + mark_safe(part2)


class SearchSelectInput(Select):
    def __init__(
        self, attrs=None, options: list[dict[str, str]] = None, *args, **kwargs
    ):
        super().__init__(*args, attrs, **kwargs)


class TestDatalist(forms.Form):
    foo = forms.CharField(
        max_length=10,
        widget=DatalistTextInput(
            attrs={
                "list": "foolist",
                "class": "input input-bordered",
            },
            datalist=["foo", "bar", "baz", "quux"],
        ),
    )


# class BaseModelForm(forms.ModelForm):
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         for visible in self.visible_fields():
#             class_str = None
#             print(visible.widget_type)
#             match visible.widget_type:
#                 case "text" | "number":
#                     class_str = "input input-bordered"
#                 case "checkbox":
#                     class_str = "checkbox"
#                 case "select" | "selectmultiple":
#                     class_str = "select select-bordered"
#                 case "clearablefile":
#                     class_str = "file-input file-input-bordered"
#                 case _:
#                     class_str = "input input-bordered"
#
#             visible.field.widget.attrs["class"] = class_str


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        exclude = ["user", "enrolled_users"]
        widgets = {
            "preview": forms.FileInput(
                attrs={"accept": "video/mp4,video/webm,video/ogg,video/mpeg"}
            )
        }


class CourseRequirementForm(forms.ModelForm):
    class Meta:
        model = CourseRequirement
        fields = ["description"]


class CourseAudienceForm(forms.ModelForm):
    class Meta:
        model = CourseAudience
        fields = ["description"]


class CourseLectureForm(forms.ModelForm):
    class Meta:
        model = CourseLecture
        exclude = ["id", "created_at", "updated_at", "order"]

core/views.py
import json
from typing import Any
from django.conf import settings
from django.core.files.storage import FileSystemStorage
import os
from django.forms import modelformset_factory
from django.http import HttpRequest, HttpResponse, HttpResponseBadRequest, QueryDict
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy

from django.utils.decorators import method_decorator
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
    View,
)
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django_htmx.http import (
    HttpResponseClientRedirect,
    reswap,
    retarget,
    trigger_client_event,
)
import django_filters
from django_filters.views import FilterView
import time
from formtools.wizard.views import SessionWizardView

from core.cart import Cart
from core.forms import (
    CourseAudienceForm,
    CourseForm,
    CourseLectureForm,
    CourseRequirementForm,
)
from core.models import (
    Course,
    CourseAudience,
    CourseLecture,
    CourseRequirement,
    CourseSection,
    Transaction,
    TransactionStatus,
)
from core.utils import htmx_redirect, inject_messages, render_html_block


def home(request):
    return render(request, "home.html")


class CourseFilter(django_filters.FilterSet):
    title = django_filters.CharFilter(lookup_expr="icontains")

    class Meta:
        model = Course
        fields = ["category"]


class CoursesListView(FilterView):
    model = Course
    template_name = "partials/course-list.html"
    context_object_name = "courses"
    filterset_class = CourseFilter
    paginate_by = 16

    def render_to_response(self, context, **response_kwargs):
        if not self.request.htmx:
            return render(self.request, "home.html")
        time.sleep(1)
        return super().render_to_response(context, **response_kwargs)


class UserCourseListView(LoginRequiredMixin, ListView):
    model = Course
    template_name = "core/user_course_list.html"
    context_object_name = "courses"

    def get_queryset(self):
        return self.request.user.enrolled_courses.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class CourseCreateView(LoginRequiredMixin, SessionWizardView):
    form_list = [
        CourseForm,
        modelformset_factory(CourseRequirement, form=CourseRequirementForm, extra=5),
        modelformset_factory(CourseAudience, form=CourseAudienceForm, extra=5),
    ]
    file_storage = FileSystemStorage(
        location=os.path.join(settings.MEDIA_ROOT, "tmp/courses")
    )

    template_name = "core/wizard_form.html"

    def done(self, form_list, form_dict, **kwargs):
        course_form = form_dict["0"]
        course = course_form.save(commit=False)
        course.user = self.request.user
        course.save()

        course_requirements = form_dict["1"].save(commit=False)
        for course_requirement in course_requirements:
            course_requirement.course = course
            course_requirement.save()

        course_audiences = form_dict["2"].save(commit=False)
        for course_audience in course_audiences:
            course_audience.course = course
            course_audience.save()
        return redirect(self.request.META.get("HTTP_REFERER"))


class CreatedCoursesListView(LoginRequiredMixin, ListView):
    model = Course
    template_name = "core/my_courses.html"
    context_object_name = "courses"
    queryset = Course.objects.order_by("-updated_at")

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        if not request.htmx or request.htmx.boosted:
            return render(request, self.template_name)
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        courses = super().get_queryset()
        return courses.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["is_creator"] = True
        return context

    def render_to_response(
        self, context: dict[str, Any], **response_kwargs: Any
    ) -> HttpResponse:
        if self.request.htmx and not self.request.htmx.boosted:
            return render_html_block(
                self.template_name, "course_list", context, self.request
            )
        return super().render_to_response(context, **response_kwargs)


class CreatorCourseDetailView(LoginRequiredMixin, DetailView):
    model = Course
    template_name_suffix = "_creator_detail"

    def post(self, request, *args, **kwargs):
        operation_type = self.request.POST.get("op-type", None)
        if not operation_type:
            return HttpResponseBadRequest("Operation Type not provided")
        match operation_type:
            case "requirement":
                description = self.request.POST.get("description", None)
                if not description:
                    messages.error(request, "Need to provide description")
                    return HttpResponseBadRequest("Description required")
                requirement = CourseRequirement.objects.create(
                    course=self.get_object(), description=description
                )
                return HttpResponse(
                    f"<li>{requirement.description}</li>", content_type="text/html"
                )
            case "audience":
                description = self.request.POST.get("description", None)
                if not description:
                    messages.error(request, "Need to provide description")
                    return HttpResponseBadRequest("Description required")
                audience = CourseAudience.objects.create(
                    course=self.get_object(), description=description
                )
                return HttpResponse(
                    f"<li>{audience.description}</li>", content_type="text/html"
                )
            case "section":
                title = self.request.POST.get("title", None)
                if not title:
                    messages.error(request, "Need to provide title")
                    return HttpResponseBadRequest("Title Required")
                section = CourseSection.objects.create(
                    course=self.get_object(),
                    title=title,
                    order=CourseSection.objects.count(),
                )
                return render_html_block(
                    "core/course_creator_detail.html",
                    "section",
                    {"section": section},
                    self.request,
                )


@method_decorator(inject_messages, name="post")
class CourseSectionDeleteView(LoginRequiredMixin, DeleteView):
    model = CourseSection

    def form_valid(self, form):
        messages.success(self.request, "Section deleted successfully")
        self.object.delete()
        return HttpResponse(status=200)


class CourseLectureCreateView(LoginRequiredMixin, CreateView):
    model = CourseLecture
    form_class = CourseLectureForm
    template_name = "partials/base-form.html"

    def form_valid(self, form) -> HttpResponse:
        self.object = form.save()
        response = render_html_block(
            "core/course_creator_detail.html",
            "lecture",
            {"lecture": self.object},
            self.request,
        )
        return retarget(response, f"#lecture-list-{self.object.section.id}")

    def get_success_url(self) -> str:
        return self.request.META.get("HTTP_REFERER")


class CourseLectureEditView(LoginRequiredMixin, UpdateView):
    model = CourseLecture
    form_class = CourseLectureForm
    context_object_name = "lecture"

    def get_success_url(self) -> str:
        return self.request.META.get("HTTP_REFERER")

    def form_valid(self, form):
        ret = super().form_valid(form)
        return htmx_redirect(
            self.request,
            reverse_lazy(
                "core:creator_course_detail",
                kwargs={"pk": self.get_object().section.course.id},
            ),
        )


@method_decorator(inject_messages, name="post")
class CourseLectureDeleteView(LoginRequiredMixin, DeleteView):
    model = CourseLecture

    def form_valid(self, form):
        messages.success(self.request, "Lecture Removed Successfully!")
        self.object.delete()
        return HttpResponse(status=200)

    def get_success_url(self) -> str:
        messages.success(self.request, "Lecture Removed Successfully!")
        return self.request.META.get("HTTP_REFERER")


@method_decorator(inject_messages, name="post")
class CourseDetailView(LoginRequiredMixin, DetailView):
    model = Course

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        course = self.get_object()
        average_rating = course.average_rating
        context["checked_star"] = (round(average_rating * 2) / 2) * 2
        context["num_stars"] = average_rating
        cart = Cart(self.request)
        context["in_cart"] = course in cart
        return context

    def post(self, request, *args, **kwargs):
        user = self.request.user
        self.object = course = self.get_object()
        if course.user == user:
            messages.error(request, "You can't buy your own course")
            response = HttpResponse(status=200)
            reswap(response, "none")
            return response

        user.enrolled_courses.add(course)
        user.save()
        cart = Cart(self.request)
        cart.remove(str(course.id))
        context = self.get_context_data()
        return render_html_block(
            "core/course_detail.html",
            "course_actions",
            context=context,
            request=self.request,
        )


class CourseContentView(LoginRequiredMixin, DetailView):
    model = Course

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-theme="emerald" class="h-full w-full">
    <head>
        <base href="" />
        <meta charset="utf-8" />
        <title>
            {% block title %}
                Udemy Clone
            {% endblock title %}
        </title>
        <meta name="description" content="Source Platform" />
        <meta name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <link href="{% static "core/ui.css" %}" rel="stylesheet" />
        <link rel="stylesheet" href="{% static "css/custom.css" %}">
        <script src="{% static 'js/htmx.min.js' %}" defer></script>
        <script defer src="{% static 'js/alpine.min.js' %}"></script>
        <script src="{% static 'js/feather.min.js' %}"></script>
        <script defer src="{% static 'js/alert.js' %}"></script>
        {% block statics %}
        {% endblock statics %}
    </head>
    <body class="h-full w-full"
          hx-boost="true"
          hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
        {% include "navbar.html" %}

        {% include "partials/alert-message.html" with message=message %}
        {% block content %}
        {% endblock content %}
        <script>feather.replace();</script>
    </body>
</html>

core/templates/home.html
{% extends "base.html" %}
{% load core_filters %}
{% load static %}
{% block statics %}
    <link href="{% static "core/home.css" %}" rel="stylesheet">
{% endblock statics %}
{% block content %}
    <h1 class="text-3xl font-bold text-center text-primary-content my-8">
        Here are some of our course offerings
    </h1>
    <main id="main-course-list"
          class="m-4 md:m-8 flex flex-wrap lg:grid lg:grid-cols-4 gap-4"
          hx-get="{% url 'core:course_list' %}?{% query_string request.GET %}"
          hx-swap="innerHTML"
          hx-trigger="load"
          hx-indicator=".course-skeleton">
        {% block course_list %}
            {% include "partials/course-list.html" with courses=courses %}
        {% endblock course_list %}
    </main>
{% endblock content %}

core/templates/navbar.html
{% load static %}
<div hx-preserve="true" class="navbar bg-base-100">
    <div class="flex-1">
        <a href="{% url 'core:index' %}" class="btn btn-ghost">
            <img src="{% static 'core/logo-udemy.svg' %}"
                 alt=""
                 width="100"
                 height="24">
        </a>
        <div class="dropdown dropdown-hover z-[9999]">
            <div x-data="{open: false}"
                 @click="if (open) { $el.blur(); } open = !open"
                 tabIndex="0"
                 role="button"
                 class="mx-7 text-primary-content">
                <span>Categories</span>
            </div>
            <ul tabIndex="0"
                class="dropdown-content menu p-2 shadow bg-base-100 w-52 text-black z-50">
                <li>
                    <button hx-get="{% url 'core:course_list' %}"
                            hx-target="#main-course-list"
                            hx-push-url="true"
                            hx-indicator="#main-course-list">All</button>
                </li>
                {% for category in course_categories %}
                    <li>
                        {% if request.path == "/" %}
                            <button hx-get="{% url 'core:course_list' %}?category={{ category.id }}"
                                    hx-target="#main-course-list"
                                    hx-indicator="#main-course-list"
                                    hx-push-url="true">
                                {{ category.name }}
                            </button>
                        {% else %}
                            <a href="{% url 'core:index' %}?category={{ category.id }}">{{ category.name }}</a>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <label class="input input-bordered flex items-center gap-2">
        <input hx-get="{% url 'core:course_list' %}"
               hx-push-url="true"
               hx-indicator="#main-course-list"
               hx-target="#main-course-list"
               hx-trigger="input changed delay:500ms, search"
               name="title"
               type="text"
               class="grow"
               placeholder="Search" 
               value="{{ request.GET.title }}"
               />
        <svg xmlns="http://www.w3.org/2000/svg"
             viewBox="0 0 16 16"
             fill="currentColor"
             class="w-4 h-4 opacity-70">
            <path fill-rule="evenodd" d="M9.965 11.026a5 5 0 1 1 1.06-1.06l2.755 2.754a.75.75 0 1 1-1.06 1.06l-2.755-2.754ZM10.5 7a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0Z" clip-rule="evenodd" />
        </svg>
    </label>
    <div class="flex-none">
        {% include "partials/nav-cart-dropdown.html" with cart=cart %}
        <div class="dropdown dropdown-end">
            <div x-data="{open: false}"
                 @click="if (open) { $el.blur(); } open = !open"
                 tabindex="0"
                 role="button"
                 class="btn btn-ghost btn-circle avatar">
                <div class="w-10 rounded-full">
                    <img alt="Tailwind CSS Navbar component" src="{% static "img/default-user-img.jpg" %}" />
                </div>
            </div>
            <ul tabindex="0"
                class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
                <li>
                    <a>Profile</a>
                </li>
                <li>
                    <a href="{% url 'core:my_courses' %}">My Courses</a>
                </li>
                <li>
                    <a href="{% url 'core:user_courses' %}">Bought Courses</a>
                </li>
                <li>
                    <a>Settings</a>
                </li>
                <li>
                    <button hx-post="{% url 'logout' %}" hx-target="body" hx-push-url="true">
                        Logout
                    </button>
                </li>
            </ul>
        </div>
    </div>
</div>

<p class="flex">

</p>

core/templates/test.html
{% load static %}
<div hx-preserve="true" class="navbar bg-base-100">
    <div class="flex-1">
        <a href="{% url 'core:index' %}" class="btn btn-ghost">
            <img src="{% static 'core/logo-udemy.svg' %}"
                 alt=""
                 width="100"
                 height="24">
        </a>
        <div class="dropdown dropdown-hover z-[9999]">
            <div tabIndex="0" role="button" class="mx-7 text-primary-content">
                <span>Categories</span>
            </div>
            <ul tabIndex="0"
                class="dropdown-content menu p-2 shadow bg-base-100 w-52 text-black z-50">
                <li>
                    <a>Item 1</a>
                </li>
                <li>
                    <a>Item 2</a>
                </li>
                <li>
                    <a>Item 3</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="flex-none">
        <div class="dropdown dropdown-end">
            <div tabindex="0" role="button" class="btn btn-ghost btn-circle">
                <div class="indicator">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         class="h-5 w-5"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />
                    </svg>
                    <span class="badge badge-sm indicator-item">{{ cart|length }}</span>
                </div>
            </div>
            <div tabindex="0"
                 class="mt-3 z-[1] card card-compact dropdown-content w-52 bg-base-100 shadow">
                <div class="card-body">
                    <span class="font-bold text-lg">{{ cart|length }} Items</span>
                    <span class="text-info">Subtotal: ${{ cart.total_price }}</span>
                    <div class="card-actions">
                        <a href="{% url 'core:cart' %}" class="btn btn-primary btn-block">View cart</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="dropdown dropdown-end">
            <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
                <div class="w-10 rounded-full">
                    <img alt="Tailwind CSS Navbar component" src="{% static "img/default-user-img.jpg" %}" />
                </div>
            </div>
            <ul tabindex="0"
                class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
                <li>
                    <a class="justify-between">
                        Profile
                        <span class="badge">New</span>
                    </a>
                </li>
                <li>
                    <a>Settings</a>
                </li>
                <li>
                    <a>Logout</a>
                </li>
            </ul>
        </div>
    </div>
</div>